CREATE TABLE IF NOT EXISTS petitions (
    petition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    blocking_level VARCHAR(2) NOT NULL DEFAULT 'B3',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_petitions_group
        FOREIGN KEY (group_id)
        REFERENCES f_group (group_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_petitions_creator_user
        FOREIGN KEY (created_by_user_id)
        REFERENCES person (user_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_petitions_blocking_level
        CHECK (blocking_level IN ('B1', 'B2', 'B3')),
    CONSTRAINT chk_petitions_time_order
        CHECK (end_time > start_time)
);

CREATE TABLE IF NOT EXISTS petition_responses (
    petition_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    response VARCHAR(20) NOT NULL,
    responded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_petition_responses
        PRIMARY KEY (petition_id, user_id),
    CONSTRAINT fk_petition_responses_petition
        FOREIGN KEY (petition_id)
        REFERENCES petitions (petition_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_petition_responses_user
        FOREIGN KEY (user_id)
        REFERENCES person (user_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_petition_responses_response
        CHECK (response IN ('ACCEPTED', 'DECLINED'))
);

CREATE INDEX IF NOT EXISTS idx_petitions_group_time
    ON petitions (group_id, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_petitions_time_range
    ON petitions (start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_petitions_created_by_user
    ON petitions (created_by_user_id);

CREATE INDEX IF NOT EXISTS idx_petition_responses_user
    ON petition_responses (user_id);

CREATE INDEX IF NOT EXISTS idx_petition_responses_petition_response
    ON petition_responses (petition_id, response);

CREATE INDEX IF NOT EXISTS idx_group_match_user
    ON group_match (user_id);
