BEGIN;

CREATE TABLE IF NOT EXISTS public.petitions
(
    petition_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    blocking_level VARCHAR(2) NOT NULL DEFAULT 'B2',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT petitions_pkey PRIMARY KEY (petition_id)
);

CREATE TABLE IF NOT EXISTS public.petition_responses
(
    petition_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    response VARCHAR(20) NOT NULL,
    responded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT petition_responses_pkey PRIMARY KEY (petition_id, user_id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_petitions_blocking_level'
          AND conrelid = 'public.petitions'::regclass
    ) THEN
        ALTER TABLE public.petitions
            ADD CONSTRAINT chk_petitions_blocking_level
                CHECK (blocking_level IN ('B1', 'B2', 'B3'));
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_petitions_time_order'
          AND conrelid = 'public.petitions'::regclass
    ) THEN
        ALTER TABLE public.petitions
            ADD CONSTRAINT chk_petitions_time_order
                CHECK (end_time > start_time);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_petitions_group'
          AND conrelid = 'public.petitions'::regclass
    ) THEN
        ALTER TABLE public.petitions
            ADD CONSTRAINT fk_petitions_group
                FOREIGN KEY (group_id)
                REFERENCES public.f_group (group_id)
                ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_petitions_creator_user'
          AND conrelid = 'public.petitions'::regclass
    ) THEN
        ALTER TABLE public.petitions
            ADD CONSTRAINT fk_petitions_creator_user
                FOREIGN KEY (created_by_user_id)
                REFERENCES public.person (user_id)
                ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_petition_responses_response'
          AND conrelid = 'public.petition_responses'::regclass
    ) THEN
        ALTER TABLE public.petition_responses
            ADD CONSTRAINT chk_petition_responses_response
                CHECK (response IN ('ACCEPTED', 'DECLINED'));
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_petition_responses_petition'
          AND conrelid = 'public.petition_responses'::regclass
    ) THEN
        ALTER TABLE public.petition_responses
            ADD CONSTRAINT fk_petition_responses_petition
                FOREIGN KEY (petition_id)
                REFERENCES public.petitions (petition_id)
                ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_petition_responses_user'
          AND conrelid = 'public.petition_responses'::regclass
    ) THEN
        ALTER TABLE public.petition_responses
            ADD CONSTRAINT fk_petition_responses_user
                FOREIGN KEY (user_id)
                REFERENCES public.person (user_id)
                ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_petitions_group_time
    ON public.petitions (group_id, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_petitions_time_range
    ON public.petitions (start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_petitions_created_by_user
    ON public.petitions (created_by_user_id);

CREATE INDEX IF NOT EXISTS idx_petition_responses_user
    ON public.petition_responses (user_id);

CREATE INDEX IF NOT EXISTS idx_petition_responses_petition_response
    ON public.petition_responses (petition_id, response);

CREATE INDEX IF NOT EXISTS idx_group_match_user
    ON public.group_match (user_id);

COMMIT;
