-- =========================
-- Table: person
-- =========================
CREATE TABLE person (
    user_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name     VARCHAR,
    last_name      VARCHAR,
    username       VARCHAR,
    email          VARCHAR,
    google_id      VARCHAR UNIQUE,
    refresh_token  TEXT,
    access_token   TEXT,
    token_expiry   BIGINT,
    created_at     TIMESTAMP,
    updated_at     BIGINT
);

-- =========================
-- Table: f_group
-- =========================
CREATE TABLE f_group (
    group_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_name  VARCHAR
);

-- =========================
-- Table: group_match
-- Junction table between person and f_group
-- =========================
CREATE TABLE group_match (
    group_id BIGINT,
    user_id  BIGINT,
    PRIMARY KEY (group_id, user_id),
    CONSTRAINT fk_group_match_group
        FOREIGN KEY (group_id)
        REFERENCES f_group (group_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_group_match_user
        FOREIGN KEY (user_id)
        REFERENCES person (user_id)
        ON DELETE CASCADE
);

-- =========================
-- Table: calendar
-- =========================
CREATE TABLE calendar (
    calendar_id   BIGINT PRIMARY KEY,
    gcal_id       VARCHAR,
    calendar_name VARCHAR
);

-- =========================
-- Table: cal_event
-- =========================
CREATE TABLE cal_event (
    event_id       BIGINT PRIMARY KEY,
    calendar_id    BIGINT,
    priority       INT,
    event_start    TIMESTAMPTZ NOT NULL,
    event_end      TIMESTAMPTZ NOT NULL,
    event_name     TEXT,
    gcal_event_id  VARCHAR(100),
    CONSTRAINT fk_event_calendar
        FOREIGN KEY (calendar_id)
        REFERENCES calendar (calendar_id)
        ON DELETE CASCADE
);
