CREATE TABLE IF NOT EXISTS 
person (
<<<<<<< Updated upstream
	user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	username VARCHAR(12),
	email VARCHAR(25),
	google_user_id VARCHAR(255)
=======
	user_id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	username VARCHAR(12) NOT NULL,
	email VARCHAR(25) NOT NULL,
	google_user_id VARCHAR(255) NOT NULL
>>>>>>> Stashed changes
);

CREATE TABLE IF NOT EXISTS
f_group (
<<<<<<< Updated upstream
	group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	group_name VARCHAR(50)
=======
	group_id BIGSERIAL NOT NULL PRIMARY KEY,
	group_name VARCHAR(50) NOT NULL
>>>>>>> Stashed changes
);

CREATE TABLE IF NOT EXISTS
group_match (
	group_id BIGSERIAL NOT NULL REFERENCES f_group (group_id),
	user_id BIGSERIAL NOT NULL REFERENCES person (user_id),
	PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS
calendar (
	-- i think this is internal calendar id
<<<<<<< Updated upstream
	calendar_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	gcal_id VARCHAR(255),
=======
	calendar_id BIGSERIAL NOT NULL PRIMARY KEY,
	gcal_id VARCHAR(255) NOT NULL,
>>>>>>> Stashed changes
	-- unknown if needed
	calendar_name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS
cal_event (
<<<<<<< Updated upstream
	event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	calendar_id INTEGER NOT NULL REFERENCES calendar (calendar_id),
=======
	event_id BIGSERIAL NOT NULL PRIMARY KEY,
	calendar_id BIGSERIAL NOT NULL REFERENCES calendar (calendar_id),
>>>>>>> Stashed changes
	priority INTEGER,
	event_start TIMESTAMPTZ NOT NULL,
	event_duration FLOAT NOT NULL -- in hours
);
