-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cal_event
(
    event_id bigserial NOT NULL,
    calendar_id bigserial NOT NULL,
    priority integer,
    event_start timestamp with time zone NOT NULL,
    event_end timestamp with time zone,
    event_name text COLLATE pg_catalog."default",
    gcal_event_id character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT cal_event_pkey PRIMARY KEY (event_id),
    CONSTRAINT cal_event_gcal_event_id_key UNIQUE (gcal_event_id)
);

CREATE TABLE IF NOT EXISTS public.calendar
(
    calendar_id bigserial NOT NULL,
    calendar_name character varying(100) COLLATE pg_catalog."default",
    user_id bigint NOT NULL,
    CONSTRAINT calendar_pkey PRIMARY KEY (calendar_id),
    CONSTRAINT calendar_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.f_group
(
    group_id bigserial NOT NULL,
    group_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT f_group_pkey PRIMARY KEY (group_id)
);

CREATE TABLE IF NOT EXISTS public.group_match
(
    group_id bigserial NOT NULL,
    user_id bigserial NOT NULL,
    CONSTRAINT group_match_pkey PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.person
(
    user_id bigserial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    username character varying(12) COLLATE pg_catalog."default" NOT NULL,
    email character varying(25) COLLATE pg_catalog."default" NOT NULL,
    google_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    refresh_token text COLLATE pg_catalog."default",
    access_token text COLLATE pg_catalog."default",
    token_expiry bigint,
    created_at bigint,
    updated_at bigint,
    CONSTRAINT person_pkey PRIMARY KEY (user_id),
    CONSTRAINT person_google_id_key UNIQUE (google_id)
);

CREATE TABLE IF NOT EXISTS public.session
(
    sid character varying COLLATE pg_catalog."default" NOT NULL,
    sess json NOT NULL,
    expire timestamp(6) without time zone NOT NULL,
    CONSTRAINT session_pkey PRIMARY KEY (sid)
);

ALTER TABLE IF EXISTS public.cal_event
    ADD FOREIGN KEY (calendar_id)
    REFERENCES public.calendar (calendar_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.calendar
    ADD CONSTRAINT fk_person FOREIGN KEY (user_id)
    REFERENCES public.person (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS calendar_user_id_key
    ON public.calendar(user_id);


ALTER TABLE IF EXISTS public.group_match
    ADD CONSTRAINT group_match_group_id_fkey FOREIGN KEY (group_id)
    REFERENCES public.f_group (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.group_match
    ADD CONSTRAINT group_match_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.person (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;